# Creates a release using compose.py from https://github.com/CleverRaven/Cataclysm-DDA
#
# This action is triggerd by pushing any tag starting with v (e.g. v1.0.1 or v3.D)
#
# The release archive will be named using the version number from the tag (e.g. UltimateCataclysm-1.0)

on:
  push:
    branches:
      - automation

name: Make Release

env:
  COMPOSE_ARGS: --use-all --obsolete-fillers --format-json
  BUILD_DIR: build

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      timestamp: ${{ steps.get-timestamp.outputs.time }}
      release_already_exists: ${{ steps.tag_check.outputs.exists }}
    steps:
      - name: Get build timestamp
        id: get-timestamp
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 0
          format: 'YYYY-MM-DD'
      - name: Generate environmental variables
        id: generate_env_vars
        run: |
          echo "::set-output name=tag_name::${{ steps.get-timestamp.outputs.time }}"
          echo "::set-output name=release_name::Tilesets Release ${{ steps.get-timestamp.outputs.time }}"
      - name: Check if there is existing git tag
        id: tag_check
        uses: mukunku/tag-exists-action@v1.0.0
        with:
          tag: ${{ steps.generate_env_vars.outputs.tag_name }}  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        if: ${{ steps.tag_check.outputs.exists == 'false' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.generate_env_vars.outputs.tag_name }}
          tag_prefix: ""
      - name: 'Get Previous tag'
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        if: ${{ steps.tag_check.outputs.exists == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate_env_vars.outputs.tag_name }}
          release_name: ${{ steps.generate_env_vars.outputs.release_name }}
          body: |
            Full Changelog [${{ steps.previous_tag.outputs.tag }}...${{ steps.generate_env_vars.outputs.tag_name }}](https://github.com/${{ github.repository }}/compare/${{ steps.previous_tag.outputs.tag }}...${{ steps.generate_env_vars.outputs.tag_name }})
          draft: false
          prerelease: false
  builds:
    needs: release
    if: ${{ needs.release.outputs.release_already_exists == 'false' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Altica
            artifact: Altica
            tileset_dir: gfx/Altica

          - name: BrownLikeBears
            artifact: BrownLikeBears
            tileset_dir: gfx/BrownLikeBears

          - name: Chibi_Ultica
            artifact: Chibi_Ultica
            tileset_dir: gfx/Chibi_Ultica

          - name: HollowMoon
            artifact: HollowMoon
            tileset_dir: gfx/HollowMoon

          - name: Larwick_Overmap
            artifact: Larwick_Overmap
            tileset_dir: gfx/Larwick_Overmap

          - name: MShockXotto+
            artifact: MShockXotto+
            tileset_dir: gfx/MShockXotto\+

          - name: NeoDays
            artifact: NeoDaysTileset
            tileset_dir: gfx/NeoDays

          - name: Retrodays
            artifact: RetroDaysTileset
            tileset_dir: gfx/Retrodays

          - name: SurveyorsMap
            artifact: SurveyorsMap
            tileset_dir: gfx/SurveyorsMap

          - name: UltimateCataclysm
            artifact: UltimateCataclysm
            tileset_dir: gfx/UltimateCataclysm

    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install musl-dev gcc libvips-dev python3-dev python3-pip python3-wheel
          pip3 install pyvips

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build
        id: build
        run: |
          mkdir "$BUILD_DIR"
          wget -q -P "$BUILD_DIR" https://raw.githubusercontent.com/CleverRaven/Cataclysm-DDA/master/tools/gfx_tools/compose.py \
          || echo "Error: Failed to get compose.py"

          python3 "$BUILD_DIR/compose.py" $COMPOSE_ARGS "${{matrix.tileset_dir}}" "$BUILD_DIR"
          [ -f "${{matrix.tileset_dir}}/fallback.png" ] && cp "${{matrix.tileset_dir}}/fallback.png" "$BUILD_DIR/"

          release_name=${{matrix.artifact}}

          tileset_dir=../${{matrix.tileset_dir}}

          mkdir $release_name
          mv $tileset_dir/*.png            $release_name
          cp $tileset_dir/tile_config.json $release_name
          cp $tileset_dir/tileset.txt      $release_name
          cp $tileset_dir/layering.json    $release_name

          zip -r $release_name.zip $release_name

          echo ::set-output name=release_name::$release_name

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/${{ steps.build.outputs.release_name }}.zip
          asset_name: ${{ steps.build.outputs.release_name }}.zip
          asset_content_type: application/zip
